<%@ Page Title="" Language="C#" MasterPageFile="~/Master1.Master" AutoEventWireup="true" CodeBehind="AboutUS.aspx.cs" Inherits="Moderna2.AboutUS" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <h2 class="rtecenter" style="box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; font-family: Lato, sans-serif; font-weight: 300; font-style: normal; color: rgb(0, 58, 94); text-rendering: optimizelegibility; line-height: 1.4; font-size: 2rem; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-align: center; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Welcome to Moderna. We believe mRNA is the “software of life.&quot;</h2>
<p style="box-sizing: border-box; margin: 0px 0px 1.25rem; padding: 0px; font-family: Lato, sans-serif; font-weight: 400; font-size: 16px; line-height: 1.6; text-rendering: optimizelegibility; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); color: rgb(68, 68, 68); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Every cell in the body uses mRNA to provide real-time instructions to make the proteins necessary to drive all aspects of biology, including in human health and disease.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1.25rem; padding: 0px; font-family: Lato, sans-serif; font-weight: 400; font-size: 16px; line-height: 1.6; text-rendering: optimizelegibility; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); color: rgb(68, 68, 68); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    Given its essential role, we believe mRNA could be used to create a new category of medicines with significant potential to improve the lives of patients.</p>
<p style="box-sizing: border-box; margin: 0px 0px 1.25rem; padding: 0px; font-family: Lato, sans-serif; font-weight: 400; font-size: 16px; line-height: 1.6; text-rendering: optimizelegibility; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); color: rgb(68, 68, 68); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    We are pioneering a new class of medicines made of messenger RNA, or mRNA. The potential implications of using mRNA as a drug are significant and far-reaching and could meaningfully improve&nbsp;how medicines are discovered, developed and manufactured.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px 0px 1.25rem; padding: 0px; font-family: Lato, sans-serif; font-weight: 400; font-size: 16px; line-height: 1.6; text-rendering: optimizelegibility; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); color: rgb(68, 68, 68); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
    <span style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); font-family: inherit; font-size: 1rem;">Since our founding in 2010, we have worked to build&nbsp;the industry&#39;s leading&nbsp;mRNA technology platform, the infrastructure to accelerate drug discovery and early development, a rapidly expanding pipeline, and a world-class&nbsp;team. Our pipeline includes development candidates for mRNA-based vaccines and therapies spanning several therapeutic areas, and we have multiple clinical trials underway with other development candidates progressing toward the clinic. In addition, we have numerous&nbsp;discovery programs&nbsp;advancing toward development.&nbsp;</span>&nbsp;</p>
<h2 class="rtecenter" style="box-sizing: border-box; margin: 0.2rem 0px 0.5rem; padding: 0px; font-family: Lato, sans-serif; font-weight: 300; font-style: normal; color: rgb(0, 58, 94); text-rendering: optimizelegibility; line-height: 1.4; font-size: 2rem; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); text-align: center; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: bold; line-height: inherit; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);">Moderna&#39;s Mission:</strong><br style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);" />
    Deliver on the promise of mRNA science to create a new generation of transformative medicines for patients.</h2>
</asp:Content>
